package fes.aragon.inicio;

import fes.aragon.elementos.Asteroide;
import fes.aragon.elementos.ColisionAJ;
import fes.aragon.elementos.ColisionBN;
import fes.aragon.elementos.FondoImagen;
import fes.aragon.elementos.NaveEnemigo;
import fes.aragon.elementos.NaveJugador;
import fes.aragon.hilos.Hilo_Panel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Alex
 */
public class Inicio extends javax.swing.JFrame {
    
    public Inicio() {
        initComponents();
        Toolkit herram = Toolkit.getDefaultToolkit();
        Image img = herram.getImage(getClass().getResource("/fes/aragon/recursos/Icono.png"));
        this.setIconImage(img);
        this.setTitle("Space Galaxy");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.jPanel1.setFocusable(true);
        Dimension xy = this.jPanel1.getSize();
        ((Hilo_Panel) this.jPanel1).setXy(xy);
        
        FondoImagen fondo = new FondoImagen(this, xy);
        NaveEnemigo naveEnemigo = new NaveEnemigo(this, xy);
        NaveJugador naveJugador = new NaveJugador(this, xy);
        Asteroide asteroide = new Asteroide(this, xy);
        ColisionBN bn = new ColisionBN(this, naveJugador, naveEnemigo);
        ColisionAJ aj = new ColisionAJ(this, naveJugador, asteroide);

        
        ((Hilo_Panel) this.jPanel1).getComponente().add(fondo);
        ((Hilo_Panel) this.jPanel1).getComponente().add(naveEnemigo);
        ((Hilo_Panel) this.jPanel1).getComponente().add(naveJugador);
        ((Hilo_Panel) this.jPanel1).getComponente().add(asteroide);
        ((Hilo_Panel) this.jPanel1).getComponente().add(bn);
        ((Hilo_Panel) this.jPanel1).getComponente().add(aj);
        ((Hilo_Panel) this.jPanel1).setBn(bn);
        ((Hilo_Panel) this.jPanel1).setAj(aj);

        Thread hilo = new Thread((Runnable) this.jPanel1);        
        hilo.start();                   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fes.aragon.hilos.Hilo_Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
